
spring:
    datasource:
        druid:

            url: jdbc:mysql://rm-bp1rc23s40ss8j9lw.mysql.rds.aliyuncs.com:3306/05trade_app?useUnicode=true&characterEncoding=UTF-8
            username: user_05
            password: S9BlaFG9HIfmUkdT
            type: com.alibaba.druid.pool.DruidDataSource
            driver-class-name: com.mysql.jdbc.Driver
            initial-size: 10
            max-active: 100
            min-idle: 5
            max-wait: 60000
            validation-query: SELECT 1
            test-on-borrow: false
            test-on-return: false
            test-while-idle: true
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 25200000
            remove-abandoned: true
            remove-abandoned-timeout: 1800
            logAbandoned: true
            filters: stat
            pool-prepared-statement: true
            max-open-prepared-statements: 100

server:
    port: 8080

#eureka:
#  instance:
#    prefer-ip-address: true
#    ip-address: 121.43.172.116
#    non-secure-port-enabled: true
#    non-secure-port: 9004
#    instance-id: ${eureka.instance.ip-address}:${eureka.instance.non-secure-port}
#
ext:
    swagger:
        enabled: true
    activeMqConfiguration:
        brokerUrl: failover:(tcp://172.17.0.1:61616?wireFormat.maxInactivityDuration=0,tcp://172.17.0.1:61616?wireFormat.maxInactivityDuration=0)
        queueTableName: trd_mq_message
        queueName: trd_queue
        queueMaxCount: 50000
        isCreateTable: 1
    oldCashmanServerAddressConfig:
        serverAddress: 47.97.117.209:5000